main: be.garagepoort.tubingbroadcast.TubingBroadcast
name: TubingBroadcast
version: ${project.version}
description: Tubing broadcast example project
author: Garagepoort
api-version: 1.16
commands:
  broadcast:
    description: Broadcasts a message to all players
    usage: /<command>
    aliases: [br]
